name: Build Android Only

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Install Dependencies
        run: flutter pub get

      - name: Clean Build
        run: flutter clean

      - name: Pub Get Again
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: List APK Output
        run: find build/app/outputs -name "*.apk" -type f

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: StudyFlow-Android-APK
          path: build/app/outputs/flutter-apk/app-release.apk