name: Build Windows Only

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          flutter-version: '3.16.9'
          channel: 'stable'
          cache: true

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Install Dependencies
        run: flutter pub get

      - name: Clean Build
        run: flutter clean

      - name: Pub Get Again
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows

      - name: List Build Output
        run: dir build\windows\runner\Release /s

      - name: Create Windows Package
        run: |
          mkdir StudyFlow-Windows
          xcopy "build\windows\runner\Release\*" "StudyFlow-Windows\" /E /I /Y
          echo "StudyFlow for Windows - Ready to Run!" > StudyFlow-Windows\README.txt
          echo "" >> StudyFlow-Windows\README.txt
          echo "Double-click studyflow.exe to run the app" >> StudyFlow-Windows\README.txt

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: StudyFlow-Windows-Executable
          path: StudyFlow-Windows/